version: '3.4'

services:
  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data

  logstash:
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "8080:8080"
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro

  kibana:
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  healthchecks:
    ports:
      - "5602:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Contentmanagement server health check
      - HealthChecksUI__HealthChecks__0__Uri=http://store-contentmanagement/hc
      - HealthChecksUI__HealthChecks__1__Name=Customerrelations server health check
      - HealthChecksUI__HealthChecks__1__Uri=http://store-customerrelations/hc
      - HealthChecksUI__HealthChecks__2__Name=Operations health check
      - HealthChecksUI__HealthChecks__2__Uri=http://store-operations/hc
      - HealthChecksUI__HealthChecks__3__Name=Sales server health check
      - HealthChecksUI__HealthChecks__3__Uri=http://store-sales/hc
      - HealthChecksUI__HealthChecks__4__Name=Ecommerce server health check
      - HealthChecksUI__HealthChecks__4__Uri=http://store-ecommerce/hc

  store-contentmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80   

  store-customerrelations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80  
      
  store-operations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80   
      
  store-sales:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80  

  store-ecommerce:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80  
    ports:
      - "64876:80"

volumes:
  elasticsearch-data:
