version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
      interval: 10s
      retries: 5

  store.contentmanagement:
    image: ${DOCKER_REGISTRY-}storecontentmanagement
    build:
      context: .
      dockerfile: Store.ContentManagement/Dockerfile
    depends_on:
      - rabbitmq

  store.customerrelations:
    image: ${DOCKER_REGISTRY-}storecustomerrelations
    build:
      context: .
      dockerfile: Store.CustomerRelations/Dockerfile
    depends_on:
      - rabbitmq
      
  store.operations:
    image: ${DOCKER_REGISTRY-}storeoperations
    build:
      context: .
      dockerfile: Store.Operations/Dockerfile
    depends_on:
      - rabbitmq
      
  store.sales:
    image: ${DOCKER_REGISTRY-}storesales
    build:
      context: .
      dockerfile: Store.Sales/Dockerfile
    depends_on:
      - rabbitmq

  store.ecommerce:
    image: ${DOCKER_REGISTRY-}storeecommerce
    build:
      context: .
      dockerfile: Store.ECommerce/Dockerfile
    depends_on:
      - rabbitmq

